//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cshap_Mvc.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Blog_ManagementEntities : DbContext
    {
        public Blog_ManagementEntities()
            : base("name=Blog_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
